### ISSUE TITLE
Ensure that people can still access open documents

### ISSUE THREAD

**Issue by stevenjmesser** [digital-land/digital-land#345]
## What

Find all the documents we've made openly available, [including slide decks](https://github.com/search?q=org%3Adigital-land%20docs.google.com%2Fpresentation&type=code), and move these to another location while maintaining open access.

## Why

Google Drive is being decommissioned.

## Tasks

- [ ] Search the repos for all the documents we've made openly available
- [ ] Copy those documents over to a new location
- [ ] Make sure they're openly available
- [ ] Change the links to point to the new locations
