### ISSUE TITLE
Migrate posts to the service website 

### ISSUE THREAD

**Issue by stevenjmesser** [digital-land/digital-land#346]
## What

Move any technical notes, guidance, explainers or blog posts from the [old Digital Land website](https://digital-land.github.io/blog-post/) over to the service website.

## Why

Information that's useful to users should be on the main platform rather than an offshoot website.

## Tasks

- [ ] Audit and categorise the content from the old website
- [ ] Work out where it might live on planning.data.gov.uk
- [ ] Migrate the content
